version: 2

models:
  - name: STG_RAW_DATA_FROM_VIDEO
    description: "Staging Raw Data from Video"
    columns:
      - name: SURR_ID
        data_type: string
        description: "Unique Record Identifier"
        tests:
          - unique
          - not_null
          - not_empty
      - name: INGESTION_TIMESTAMP
        data_type: timestamp
        description: "Timestamp of when the data was ingested"
        tests:
          - not_null
      - name: YT_VIDEO_TITLE
        data_type: string
        description: "Title of the YouTube video"
        tests:
          - not_null
          - not_empty
      - name: SEGMENT_TITLE
        data_type: string
        description: "Title of the segment"
        tests:
          - not_null
          - not_empty
      - name: FILENAME
        data_type: string
        description: "Filename of the audio segment"
        tests:
          - not_null
          - not_empty
      - name: FORMAT_NAME
        data_type: string
        description: "Format of the audio segment"
        tests:
          - not_null
          - not_empty
      - name: SAMPLE_RATE
        data_type: int64
        description: "Sample rate of the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 8000
              max_value: 192000
      - name: CHANNELS
        data_type: int64
        description: "Number of channels in the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 8
      - name: BITS_PER_SAMPLE
        data_type: int64
        description: "Bits per sample in the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 8
              max_value: 32
      - name: DURATION
        data_type: float64
        description: "Duration of the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: BIT_RATE
        data_type: int64
        description: "Bit rate of the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: SIZE
        data_type: int64
        description: "Size of the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: CODEC_NAME
        data_type: string
        description: "Codec name of the audio segment"
        tests:
          - not_null
          - not_empty
      - name: MIN_SPEAKERS
        data_type: int64
        description: "Minimum number of speakers in the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: MAX_SPEAKERS
        data_type: int64
        description: "Maximum number of speakers in the audio segment"
        tests:
          - not_null
      - name: TEAM
        data_type: string
        description: "Team name"
        tests:
          - not_null
          - not_empty
          - relationships:
              to: source('SRC', 'team_members')
              field: team
      - name: TEXT
        data_type: string
        description: "Transcription of the audio segment"
        tests:
          - not_empty
      - name: GPT_CLARITY
        data_type: int64
        description: "Clarity rating of the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -1
              max_value: 5
      - name: GPT_INTENSITY
        data_type: int64
        description: "Intensity rating of the audio segment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -1
              max_value: 5
      - name: GPT_SUMMARY
        data_type: string
        description: "Text summary of the audio segment"
        tests:
          - not_null
          - not_empty
      - name: RECORD_SOURCE
        data_type: string
        description: "Table source"
        tests:
          - not_null
          - not_empty

  - name: STG_TEAM_MEMBERS
    description: "Staging Team roster information including historical data"
    columns:
      - name: SURR_ID
        data_type: string
        description: "Unique Record Identifier"
        tests:
          - unique
          - not_null
          - not_empty
      - name: PLAYER_NAME
        data_type: string
        description: "Player name"
        tests:
          - not_null
          - not_empty
      - name: TEAM
        data_type: string
        description: "Current Team Name"
        tests:
          - not_null
          - not_empty
      - name: EFFECTIVE_START_DATE
        data_type: date
        description: "Date when the player joined the team"
        tests:
          - not_null
      - name: EFFECTIVE_END_DATE
        data_type: date
        description: "Date when the player left the team (NULL if active)"
      - name: IS_CURRENT
        data_type: boolean
        description: "Indicates whether this is the current team (TRUE = Active, FALSE = Historical)"
        tests:
          - not_null
      - name: CREATED_AT
        data_type: timestamp
        description: "Record creation timestamp"
        tests:
          - not_null
      - name: UPDATED_AT
        data_type: timestamp
        description: "Last update timestamp"
        tests:
          - not_null
      - name: RECORD_SOURCE
        data_type: string
        description: "Table source"
        tests:
          - not_null
          - not_empty

sources:
  - name: SRC
    database: dataengcamp-427114
    schema: lolesports_voice_analytics
    tables:
      - name: raw_data_from_video
        description: "Source Raw Data from Video"
        columns:
          - name: ingestion_timestamp
            data_type: timestamp
            description: "Timestamp of when the data was ingested"
            tests:
              - not_null
          - name: yt_video_title
            data_type: string
            description: "Title of the YouTube video"
            tests:
              - not_null
          - name: title
            data_type: string
            description: "Title of the segment"
            tests:
              - not_null
          - name: filename
            data_type: string
            description: "Filename of the audio segment"
            tests:
              - not_null
          - name: format_name
            data_type: string
            description: "Format of the audio segment"
            tests:
              - not_null
          - name: sample_rate
            data_type: int64
            description: "Sample rate of the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 8000
                  max_value: 192000
          - name: channels
            data_type: int64
            description: "Number of channels in the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 1
                  max_value: 8
          - name: bits_per_sample
            data_type: int64
            description: "Bits per sample in the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 8
                  max_value: 32
          - name: duration
            data_type: float64
            description: "Duration of the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: bit_rate
            data_type: int64
            description: "Bit rate of the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: size
            data_type: int64
            description: "Size of the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: codec_name
            data_type: string
            description: "Codec name of the audio segment"
            tests:
              - not_null
          - name: min_speakers
            data_type: int64
            description: "Minimum number of speakers in the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 1
          - name: max_speakers
            data_type: int64
            description: "Maximum number of speakers in the audio segment"
            tests:
              - not_null
          - name: team
            data_type: string
            description: "Team name"
            tests:
              - not_null
              - relationships:
                  to: source('SRC', 'team_members')
                  field: team
          - name: text
            data_type: string
            description: "Transcription of the audio segment"
          - name: gpt_clarity
            data_type: int64
            description: "Clarity rating of the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: -1
                  max_value: 5
          - name: gpt_intensity
            data_type: int64
            description: "Intensity rating of the audio segment"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: -1
                  max_value: 5
          - name: gpt_summary
            data_type: string
            description: "Text summary of the audio segment"
            tests:
              - not_null

      - name: team_members
        description: "Team roster information including historical data"
        columns:
          - name: player_name
            data_type: string
            description: "Player name"
            tests:
              - not_null
          - name: team
            data_type: string
            description: "Current Team Name"
            tests:
              - not_null
          - name: effective_start_date
            data_type: date
            description: "Date when the player joined the team"
            tests:
              - not_null
          - name: effective_end_date
            data_type: date
            description: "Date when the player left the team (NULL if active)"
          - name: is_current
            data_type: boolean
            description: "Indicates whether this is the current team (TRUE = Active, FALSE = Historical)"
            tests:
              - not_null
          - name: created_at
            data_type: timestamp
            description: "Record creation timestamp"
            tests:
              - not_null
          - name: updated_at
            data_type: timestamp
            description: "Last update timestamp"
            tests:
              - not_null
