default_stages: [commit, push]
exclude: ^tests/resources/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: (?x)^dbt_models/.*
      - id: trailing-whitespace
        exclude: (?x)^dbt_models/.*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format
  # -   repo: local
  #     hooks:
  #     - id: pytest
  #       name: test python code
  #       entry: bash -c 'PYTHONPATH=./airflow pytest'
  #       language: system
  #       pass_filenames: false
  #       always_run: true
