name: 'dbt_models'
version: '1.0.0'
config-version: 2

profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target" 
clean-targets:    # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  dbt_models:
    +materialized: view

    staging:    
      +materialized: view
      +schema: STAGING

    refined: 
      +materialized: table
      +schema: REFINED

    marts:  
      +materialized: table
      +schema: MARTS
