default:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEY') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "schema"
      location: "US"
      priority: interactive