default:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: service-account
      keyfile_json: "{{ env_var('GCP_SERVICE_ACCOUNT_KEY') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "lolesports_voice_analytics"
      location: "US"
      priority: interactive